# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call Kosmic algorithm
#' 
#' @export
call_kosmic_alg <- function(inputVec, n, decimals, bootstrap, bootstrap_seed, threads, t1min, t1max, t2min, t2max, sd, tol) {
    .Call('_kosmic_call_kosmic_alg', PACKAGE = 'kosmic', inputVec, n, decimals, bootstrap, bootstrap_seed, threads, t1min, t1max, t2min, t2max, sd, tol)
}

