# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call kosmic algorithm
#' 
#' @keywords internal
kosmic_impl <- function(input_vector, decimals, bootstrap, t1min, t1max, t2min, t2max, sd, tol) {
    .Call('_tidykosmic_kosmic_impl', PACKAGE = 'tidykosmic', input_vector, decimals, bootstrap, t1min, t1max, t2min, t2max, sd, tol)
}

#' Resample data using the same code as the kosmic agorithm
#' 
#' @keywords internal
kosmic_resamples_impl <- function(results, counts, replicates, settings) {
    .Call('_tidykosmic_kosmic_resamples_impl', PACKAGE = 'tidykosmic', results, counts, replicates, settings)
}

